const express = require("express")
const helmet = require("helmet")
const cors = require("cors")
const users = require("../routes/users")
const performances = require("../routes/performances")
const departments = require("../routes/departments")
const experiences = require("../routes/experiences")
const skills = require("../routes/skills")
const leaves = require("../routes/leaves")
const meetings = require("../routes/meetings")
const login = require("../routes/login")
const notifications = require("../routes/notifications")
const tickets = require("../routes/tickets")
const error = require("../middlewares/error")
const mails = require("../routes/mail")
const messages = require("../routes/messages")
const reviews = require("../routes/reviews")
const chats = require("../routes/chats")
const comments = require("../routes/comments")

module.exports = function (app) {
  app.use(express.urlencoded({ extended: true }))
  app.use(express.json())
  app.use(helmet())
  app.use(cors())
  require("../web sockets/chat")(app)
  app.use("/notifications", notifications)
  app.use("/users", users)
  app.use("/departments", departments)
  app.use("/experiences", experiences)
  app.use("/performances", performances)
  app.use("/skills", skills)
  app.use("/tickets", tickets)
  app.use("/verify-email", mails)
  app.use("/leaves", leaves)
  app.use("/meetings", meetings)
  app.use("/messages", messages)
  app.use("/reviews", reviews)
  app.use("/login", login)
  app.use("/chats", chats)
  app.use("/comments", comments)
  app.use(error)
}
