version: "3.9"
services:
  api:
    build: ..
    ports:
      - "9876:9876"
    volumes:
      - .:/app
  database:
    image: postgres:15-alpine
    volumes:
      - "/db"
    ports:
      - "1234:1234"
